common/urls.py
from django.conf.urls import patterns, url
from common import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'douban.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'myapp/login.html'}),
        
    url(r'^$', views.base, name='base'),
    url(r'^init_username/$', views.init_username, name='init_username'),
    
)

privatemanager/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-


from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'privatemanager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^common/', include('common.urls')),
    url(r'^procedure_article/', include('procedure_article.urls')),
    url(r'^mytask/', include('mytask.urls')),
    (r'^comments/', include('django_comments.urls')),
    
)

procedure_article/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-


from django.conf.urls import patterns, url
from procedure_article import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'privatemanager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^init_search/$', views.init_search , name='init_search'),

    url(r'^hello/$', views.hello , name='hello'),
    
    url(r'^init/$', views.init , name='init'),
    url(r'^add/$', views.add , name='add'),

    url(r'^articles/(?P<article_id>\d+)/update/$', views.update , name='update'),
    url(r'^articles/(?P<article_id>\d+)/detail/$', views.detail , name='detail'),
    
    url(r'^articles/query/$', views.search , name='search'),
    url(r'^articles/query/type/(?P<type_id>\d+)/$', views.query_by_type , name='query_by_type'),
    url(r'^articles/query/keyword/(?P<keyword>\S+)/$', views.query_by_keyword , name='query_by_keyword'),
    url(r'^articles/query/author/(?P<author>\S+)/$', views.query_by_author , name='query_by_author'),
    
    url(r'^tongji/(?P<params>\S+)/$', views.tongji , name='tongji'),
    
)

procedure_article/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from django.db import models
from datetime import datetime

# Create your models here.
class Type(models.Model):
    
    name = models.CharField('类别名称' , max_length=50 , null=False , default='python study')
    parentId = models.IntegerField('上级编号', null=False , default=0)
    parentName = models.CharField('上级名称', max_length=50 , null=False , default='Python')
    state = models.BooleanField('启用' , null=False , default=True)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = '文章分类'
        
class Article(models.Model):
    type = models.ForeignKey(Type)
    
    title = models.CharField('文章标题' , max_length=200 , null=False , default='python study')
    jianjie = models.CharField('文章简介' , max_length=200, null=True , default='python study')
    keyword = models.CharField('关键字'  , max_length=200 , null=True , default='python ')
    content = models.TextField('内容' , null=False, default='python study')
    author = models.CharField('作者' , max_length=40 , default='wangxin')
    publishdate = models.DateField('发布时间' , null=False , default=datetime.today())
    state = models.BooleanField('启用' , null=False , default=True)
    
    def __unicode__(self):
        return self.title
    
    class Meta :
        verbose_name_plural = '文章'
        
class Comment(models.Model):
    article = models.ForeignKey(Article)
    title = models.CharField('评论标题' , max_length=200 , null=False , default='我的评论')
    content = models.TextField('评论内容' , null=False , default='python study')
    author = models.CharField('作者' , max_length=40 , default='wangxin')
    publishdate = models.DateField('发布时间' , null=False , default=datetime.today())
    state = models.BooleanField('启用' , null=False , default=True)
    
    def __unicode__(self):
        return self.title
    
    class Meta :
        verbose_name_plural = '评论'
    
    
    
    

procedure_article/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from django import forms
from django.forms import ModelForm
from procedure_article.models import Type, Article, Comment
from crispy_forms.bootstrap import  *
from crispy_forms.helper import Layout , FormHelper
from crispy_forms.layout import Submit , Reset


class ArticleForm(ModelForm):
    
    KEY_WORD_CHOICES = (
        ('python', 'python'), ('django', 'django'),
        ('mysql', 'mysql'), ('oracle', 'oracle'),
        ('sqlserver', 'sqlserver'), ('jquery', 'jquery'),
        ('apache', 'apache'), ('bootstrap', 'bootstrap'),
        (u'数据结构', u'数据结构'), ('SVN', 'SVN'), ('Git', 'Git'),
    )

    # 文章作者
    author = forms.CharField(
        label=u'作者',
        max_length=30 ,
        required=True ,
        error_messages={'required': u'请输入文章作者姓名', 'error':u'作者姓名做多可输入30个字符'},
    )
    # 文章类型 
    type = forms.ModelChoiceField(
        label=u'类型 ',
        empty_label=u'请选择文章类别' ,
        queryset=Type.objects.filter(state=True).exclude(parentId=0),
        to_field_name='id',
        required=True ,
        error_messages={'required': u'请选择文章类型'},
    )
    # 关键字
    keyword = forms.MultipleChoiceField(
        label=u'关键字',
        choices=KEY_WORD_CHOICES,
        widget=forms.CheckboxSelectMultiple(),
        error_messages={'required': u'请选择关键字'},
    )  
    # 文章标题
    title = forms.CharField(
        label=u'标题',
        max_length=200 ,
        required=True ,
        error_messages={'required': u'请输入文章标题', 'error':u'文章标题做多可输入200个字符'},
    )
    # 文章简介
    jianjie = forms.CharField(
        label=u'简介',
        max_length=200 ,
        required=True ,
        error_messages={'required': u'请添加文章概要', 'error':u'文章简介做多可输入200个字符'},
    )
    # 文章内容
    content = forms.Textarea()

    class Meta:
        model = Article
        fields = [ 'author' , 'type', 'keyword' , 'title', 'jianjie' , 'content' ]
        
        
    def __init__(self , *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.layout = Layout(
            'author',
            'type' ,
            InlineCheckboxes('keyword'),
            'title' ,
            'jianjie',
            'content',
            FormActions(
                Submit('save', u'保存'),
                Reset('reset', u'重置'),
            )
        )
        
        
        
class CommentForm(ModelForm):
    content = forms.Textarea()
   
    class Meta:
        model = Comment
        fields = ['content' ]
        
    def __init__(self , *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        
        
        
        
    

procedure_article/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from django.template.context import RequestContext
sys.setdefaultencoding('utf-8')

from django.shortcuts import render , get_object_or_404, render_to_response
from django.http import HttpResponse , HttpResponseRedirect
from procedure_article.models import Type , Article 
from procedure_article.forms import ArticleForm 
from procedure_article import utils
import logging
from common import const
from django.db.models.aggregates import Count



# 初始化 logger
LOG = logging.getLogger(__name__)


# Create your views here.

def hello(request):
    return HttpResponse("hello world ")

def _init(request , template_name , data):
    
    # 获取文章类别
    type_set = Type.objects.filter(state=True).exclude(parentId=0)
    type_list = []
    for t in type_set:
        _dict = {}
        _dict['name'] = t.name 
        _dict['id'] = t.id 
        _dict['count'] = Article.objects.filter(state=True).filter(type=t).count()
        type_list.append(_dict)
        
    # 初始化关键字
    keyword_set = ['python', 'django', 'mysql', 'oracle', 'sqlserver', 'jquery' , 'apache' , 'bootstrap' , u'数据结构' , 'SVN' , 'Git']
    
    # 初始化文章列表
    article_new_set = Article.objects.all().order_by('-id')[:10]
    
    # 加入data中
    data['keyword_set'] = keyword_set
    data['article_new_set'] = article_new_set
    data['type_list'] = type_list
    
    return render_to_response(template_name , data , context_instance=RequestContext(request))

# 初始化显示全部
def _query(request , searchCondition):
    articles = utils.query(request, searchCondition)
        
    template_name = 'procedure_article/index.html'
    init_data = {'articles' : articles}
    return  _init(request , template_name , init_data)

# 文章增改操作
def _opreate(request , instance):
    form = None 
    if request.method == 'POST' :
        keyword_str = ''
        for key in request.POST.getlist('keyword'):
            keyword_str += key + ' '
            
        form = ArticleForm(request.POST , request.FILES , instance=instance)
        if form.is_valid():
            article = form.save(commit=False)
            article.keyword = keyword_str
            article.save()
            LOG.debug(request.user.__unicode__() + u': 操作' + article.title + u'成功')
            return HttpResponseRedirect('/procedure_article/init/')
    else :
        form = ArticleForm(instance=instance) 
    template_name = 'procedure_article/article_operate.html'
    init_data = {'form' : form}
    return _init(request , template_name, init_data)

# 获取绘制统计图需要的option书
# _type='column' , _set , _categories , _terms_name , _terms_val , _chart_text , _x_axis_text
def _get_options(params , _set):
    options = {}
    if params == 'column' :
        options = {
           '_type' : 'column' ,
           '_set' : _set,
           '_categories' : 'type__name',
           '_terms_name' : u'发布数量',
           '_terms_name_list' : [u'发布数量'],
           '_terms_val'  : Count('id'),
           '_chart_text' : u'根据文章类别统计发布数量' ,
           '_x_axis_text' : u'类别' ,
       }
    elif params == 'line' :
        options = {
           '_type' : 'line' ,
           '_set' : _set,
           '_categories' : 'publishdate',
           '_terms_name' : u'发布数量',
           '_terms_name_list' : [u'发布数量'],
           '_terms_val'  : Count('id'),
           '_chart_text' : u'根据发布日期统计发布数量' ,
           '_x_axis_text' : u'发布日期' ,
       }
    return options 

# #
# #   查询相关的操作 
# #
# 初始化，查询全部
def init(request):
    # 初始化文章列表
    return _query(request, None)

# 根据类别查询
def query_by_type(request , type_id=1):
    searchCondition = {
        'type' : int(type_id)
    }
    return _query(request, searchCondition)
    
# 根据关键字查询
def query_by_keyword(request, keyword='django'):
    searchCondition = {
        'keyword__icontains' : str(keyword)
    }
    return _query(request, searchCondition)

def query_by_author(request , author='wangxin'):
    searchCondition = {
        'author__icontains' : str(author)
    }
    return _query(request, searchCondition)

# 查询
def search(request):
    if request.method == 'POST':
        searchCondition = {
            'keyword__icontains' : request.POST['txt_search']
        }
        return _query(request, searchCondition)
    else :
        return _query(request, None)

# #
# #   文章增删改操作
# #
# 添加文章
def add(request):
    if request.user.has_perm(const.PERMESSION_ADD_ARTICLE) :
        LOG.debug(request.user.__unicode__() + u': 添加文章 ')
        return _opreate(request , None)
    else :
        return HttpResponseRedirect('/procedure_article/init/')
    
# 修改文章
def update(request , article_id):
    if request.user.has_perm(const.PERMESSION_CHANGE_ARTICLE) :
        article = Article.objects.get(pk=article_id)
        LOG.debug(request.user.__unicode__() + u': 修改文章')
        return _opreate(request , article)
    else :
        return HttpResponseRedirect('/procedure_article/init/')

# 显示文章详情 , 发布评论 ,评论时验证用户登录
def detail(request, article_id=1):    
    # 文章
    article = article_pre = article_next = None 
    if article_id is not None :
        try :
            article = get_object_or_404(Article , pk=article_id)
            article_list = Article.objects.filter(state=True).order_by('publishdate')
            dict = utils.get_neighbour(article , article_list)
            article_pre = dict['pre']
            article_next = dict['_next'] 
        except Exception as er :
            LOG.error('error : ' + str(er))
            print er
            pass 
    template_name = 'procedure_article/article_detail.html'
    init_data = {
        'article' : article , 'article_pre' : article_pre , 'article_next' : article_next
    }
    return _init(request , template_name , init_data)

# #
# # 文章的统计操作
# # 
# 绘制统计图
def tongji(request, params):
    # 绘制统计图
    _set = Article.objects.filter(state=True)
    _options = _get_options(params , _set)
    pivchtChart = utils.draw_pivot_chart(_options)
    init_data = {'_set' : _set , '_options':_options , 'pivchtChart' : pivchtChart }
    template_name = 'procedure_article/tongji.html'
    return _init(request , template_name , init_data)
        

    





    

procedure_article/templates/procedure_article/article_base.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet"  href="{% static 'procedure_article/css/article_base.css' %}" >
<div class="main">
	<div class="row">
		<div id="content" class="hfeed col-xs-14 col-sm-10 col-md-8 col-lg-8">
			<ol class="breadcrumb">
				<li>
					<a href="/procedure_article/init/">首页</a>
				</li>
				<li>
					<a href="#">Library</a>
				</li>
				<li class="active">
					Data
				</li>
			</ol>
			{% block main %}{% endblock %}
		</div>
		<div id="sidebar" class="col-xs-6 col-sm-5 col-md-4 col-lg-4">
			<aside id="widget-welcome" class="widget panel panel-default">
				<div class="panel-heading">
					欢迎！
				</div>
				<div class="panel-body">
					<p>
						欢迎来到<a href="http://127.0.0.1:8000/procedure_article/init/">德芙小猪的博客</a>.如果您觉得这个博客还不错，可以从<a href="#">这里</a>下载源代码自定义自己的博客.
					</p>
				</div>
			</aside>
			<aside id="widget-categories" class="widget panel panel-default">
				<div class="panel-heading">
					类别
				</div>
				<ul class="category-root list-group">
					{% for t2 in type_list %}
					<li class="list-group-item">
						<span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
						&nbsp;<a href="/procedure_article/articles/query/type/{{ t2.id }}/"
						title="{{ t2.name }}" rel="tag category" >{{ t2.name }} </a>
						&nbsp; <span class="label label-info" style="float: right;"> {{ t2.count  }}文章 </span>
					</li>
					{% endfor %}
				</ul>
			</aside>
			<aside id="widget-recents" class="widget panel panel-default">
				<div class="panel-heading">
					最近日志
				</div>
				<ul class="list-group">

					{% for article in article_new_set %}
					<li class="list-group-item">
						<span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span>&nbsp;&nbsp; <a href="/procedure_article/articles/{{ article.id }}/detail/" title="{{ article.title }}" rel="bookmark">{{article.title}}</a>
					</li>
					{% endfor %}
				</ul>
			</aside>
			<aside id="widget-comments" class="widget panel panel-default">
				<div class="panel-heading">
					最近的评论
				</div>
				<div class="panel-body" id="recent-comments">
					<ul class="ds-recent-comments" data-num-items="10" data-show-avatars="1" data-show-time="1" data-show-admin="1" data-excerpt-length="70"></ul>
				</div>
			</aside>
			<aside id="widget-comments" class="widget panel panel-default">
				<div class="panel-heading" >
					最近的访客
				</div>
				<div class="panel-body" id="recent-comments">
					<ul class="ds-recent-visitors"></ul>
				</div>
			</aside>
			<aside id="widget-tags" class="widget panel panel-default">
				<div class="panel-heading">
					关键字
				</div>
				<div class="panel-body">
					<ul class="list-inline tag-cloud">
						{% for k in keyword_set %}
						<li>
							<a href="/procedure_article/articles/query/keyword/{{ k}}/" title="{{ k }}"class="tag-1"
							data-toggle="tooltip" data-placement="top"> <span class="badge">{{ k }}</span> </a>
						</li>
						{% endfor %}
					</ul>
				</div>
			</aside>
			{% if perms.procedure_article.change_article %}
			<aside id="widget-tags" class="widget panel panel-default">
				<div class="panel-heading">
				文章操作
				</div>
				<div class="panel-body">
					<a href="/procedure_article/add/">添加文章</a>
				</div>
			</aside>
			{% endif %}
		</div>
	</div>
</div>
<script>
	var duoshuoQuery = {
		short_name : "privatemanager",
		sso : {
			login : "http://127.0.0.1:8000/accounts/ssologin/", //替换为你自己的回调地址
			logout : "http://127.0.0.1:8000/accounts/logout/"//替换为你自己的回调地址
		}
	};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';
		ds.async = true;
		ds.src = 'http://static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds);
	})(); 
</script>
{% endblock %}

procedure_article/templates/procedure_article/article_detail.html
{% extends 'procedure_article/article_base.html '%}
{% load staticfiles %}
{% load duoshuo_tags %}
{% block main %}
<!--article  -->
<div class="panel panel-default">
	<div class="panel-heading">
		<header class="entry-header">
			<h2 class="panel-title"><a href="/2014/12/29/angularjs-14-2015/" title="{{ article.title }}" rel="bookmark" style="font-size: 24px; color: #337AB7"> {{ article.title }} </a>
			<hr style="margin: 5px 0 10px 0;">
			<p class="entry-info" style="font-size: 14px;">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span>

				<a href="#" class="fn url nickname" rel="author" title="显示所有{{ article.author}}' 的评论">{{ article.author }}</a>
				<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
				<time class="published" datetime="2014-12-29T10:03:45" pubdate="pubdate">
					{{ article.publishdate|date:"Y-m-d"}}
				</time>
				<span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
				<a href="/procedure_article/articles/query/type/{{ article.type.id }}/" title="显示所有前端日志" style="padding-left: 4px;" rel="tag category">{{article.type}}</a>
			</p></h2>
		</header>
	</div>
	<div class="panel-body">
		<div class="entry-body">
			<div class="entry-content">
				{{article.content|safe}}
			</div>
		</div>

	</div>
	<div class="panel-footer">
		<p class="entry-tags">
			<span class="glyphicon glyphicon-tags"><strong>关键字 :</strong>{% for k in article.keyword.split %} <a href="/procedure_article/articles/query/keyword/{{ k}}/">{{ k }}</a> {% endfor %}</span>
		</p>
		<p class="entry-tags">
			<span class="glyphicon glyphicon-bookmark"><strong>缩略URL:</strong><a href="#" title="{{article.title}}" rel="shortlink"> http://privatemanager.com/ </a></span>
		</p>
	</div>
</div>
<div class="entry-prev-next">
	<ul class="pager">
		{% if article_next %}
		<li class="next">
			<a href="/procedure_article/articles/{{article_next.id}}/detail/" title="{{ article_next.title }}" rel="next"> {{ article_next.title }}→ </a>
		</li>
		{% endif %}
		{% if article_pre %}
		<li class="previous">
			<a href="/procedure_article/articles/{{article_pre.id}}/detail/" title="{{ article_pre.title }}" rel="prev"> ← {{ article_pre.title }} </a>
		</li>
		{% endif %}
	</ul>
</div>
<hr/>
{% duoshuo_comments %}

{% endblock %} 

procedure_article/templates/procedure_article/article_operate.html
{% extends 'procedure_article/article_base.html '%}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form  form.helper 'bootstrap3' %}
{% block main %}
<h4 align="center"> 编写文章 </h4>
<hr />
{% crispy form %} 
<script type="text/javascript" src="{% static 'procedure_article/tinymce/js/tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript">
	tinymce.init({
		selector : "textarea"
	}); 
</script>
{% endblock %}

procedure_article/templates/procedure_article/index.html
{% extends 'procedure_article/article_base.html '%}
{% load staticfiles %}
{% block main %}
{% load pagination_tags %}
{% autopaginate articles 10 %}
<h4>文章列表</h4>
<hr />
<div>
	<div>
		{% for article in articles %}
		<div class="media">
			<a class="media-left" href="#"> {% if article.type.name == "DJANGO学习" %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/django.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% elif "python" in article.type.name|lower  %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/python.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% elif article.type.name == "Git" %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/git.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% elif article.type.name == "Jquery学习" %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/jquery.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% elif article.type.name == "SVN" %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/svn.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% elif article.type.name == "Apache" %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/apache.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% elif article.type.name == "bootstrap模板学习" %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/bootstrap.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% elif article.type.name == "MySQL" %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/mysql.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% else %} <img class="media-object" data-src="holder.js/64x64" alt="64x64" src="{% static 'common/imgs/django.jpg'%}"
			data-holder-rendered="true" style="width: 64px; height: 64px;"> {% endif %} </a>
			<div class="media-body" style="width:800px;">
				<h3 class="media-heading"><a href="/procedure_article/articles/{{ article.id }}/detail/">{{ article.title }}</a></h3>
				<p>
					&nbsp;
				</p>
				<p>
					{{ article.jianjie }}&nbsp;&nbsp;.......
					<span style="float: right;"><a href="/procedure_article/articles/{{ article.id }}/detail/">浏览更多</a></span>
				</p>
				<p>
					<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; <a href="/procedure_article/articles/query/author/{{article.author}}/" class="fn url nickname" rel="author"><small> <b>{{ article.author }}</b></small></a>
					&nbsp;&nbsp;<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
					<time class="published" datetime="2014-12-29T10:03:45" pubdate="pubdate">
						{{ article.publishdate|date:"Y-m-d"}}
					</time>
					&nbsp;&nbsp;<span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>&nbsp; <a href="/procedure_article/articles/query/type/{{ article.type.id }}/" rel="tag category"><small> <b>{{ article.type }}</b></small></a>&nbsp;
					{% for k in article.keyword.split %}
					<a href="/procedure_article/articles/query/keyword/{{ k }}/"><span class="badge"><small>{{ k }}</small></span></a>
					{% endfor %}
					&nbsp;<small><b>评论</b></small>
					<span class="ds-thread-count" data-thread-key="{{article.id}}" data-count-type="comments"></span>
				</p>
				{% if perms.procedure_article.change_article %}
					<div style="float: right;">
					<a  class="btn btn-primary" role="button" href="/procedure_article/articles/{{article.id}}/update">修改文章</a>
					</div>
				{% endif %}
			</div>
		</div>
		<hr />
		{% endfor %}
	</div>
</div>
{% paginate %}
<script>
	var duoshuoQuery = {
		short_name : "privatemanager"
	};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';
		ds.async = true;
		ds.src = 'http://static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds);
	})(); 
</script>
{% endblock %}

procedure_article/templates/procedure_article/tongji.html
{% extends 'procedure_article/article_base.html '%}
{% load staticfiles %}
{% block main %}
<script src ="http://code.highcharts.com/highcharts.js"></script>
{% load chartit  %}
 {{ pivchtChart|load_charts:"show_charts" }}
<p>
	统计报表
</p>
<div id = "show_charts">按文章列别统计发布的文章</div>

{% endblock %}